### ISSUE TITLE
Basic setup for Quantum Computing

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework1G1#22]
@WildJimmy Can you elaborate on the basic steps we need to follow to implement classical arithmetic functions (e.g., division) on IBM Quantum Computer? It would be helpful if you could share the process that how you did your task on this homework.
 Thanks in advance.

**Comment by WildJimmy** [comment]
Sure! The process varies based on the function since you need a different quantum circuit, but the main idea is you use the qiskit library in python to create and manipulate your quantum circuit. Actually knowing what kind of circuit to make is the tricky part, but for that I would definitely just recommend using Bard. For example, I got a pretty in depth response for your group's algorithm (division) by asking "Could you write me code that implements a division function on a quantum computer with qiskit?"

That said, you will probably still have to troubleshoot a bit, but it will definitely get you a good amount of the way.

**Comment by reshnashrestha** [comment]
Yeah, I tried this ... hope this will help. Thanks.
