### ISSUE TITLE
Help from ChatGPT..

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework1G1#26]
While writing the documentation file, I guess it's fine to include the ChatGPT explanation????, because I don't think I can explain better than ChatGPT. 
@laserlab

**Comment by WildJimmy** [comment]
In my opinion it's okay to refer to, but you should cite a source for anything too complex. It's definitely a good resource to help you understand things though. I only say this because I personally have received some incorrect information from AI during the course of this project, so I'm feeling cautious

**Comment by AhmedCode99** [comment]
It is perfectly fine to use chatgpt, just make sure that the AI gives you a correct response. Because they do make errors.

**Comment by laserlab** [comment]
Be aware though that you should always cite the origin of work done by others. If that is the case you can close this issue.
